server:
  port: 8090
spring:
  datasource:
    # mysql 8.0 数据库配置
    url: jdbc:mysql://193.112.188.180:3306/masterdata?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&allowMultiQueries=true
    username: qinjee
    password: qinjee2019
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    cluster:
      nodes: 193.112.188.180:7001,193.112.188.180:7002,193.112.188.180:7003,193.112.188.180:7004,193.112.188.180:7005,193.112.188.180:7006
      max-redirects: 6
    timeout: 2000
    password: qinjee2019
logging:
  level:
    com.qinjee.admin.mapper: debug
  pattern:
    dateformat: yyyy-MM-dd hh:mm:ss
  file:
    name: dhr-admin.log

pagehelper:
  helperDialect: mysql  #数据库
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
